name: Test New Template

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v2
      with:
        repository: "Ruby-Starter-Kits/Docker-Rails-Template"
        path: App
        persist-credentials: false
    - uses: actions/checkout@v2
      with:
        repository: 'Ruby-Starter-Kits/Docker-Rails-Generator'
        path: Docker-Rails-Generator
        persist-credentials: false
    - name: Set up Ruby 3.0
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.1
        bundler: none
    - name: Build Environment for building app
      run: |
        cd $GITHUB_WORKSPACE/Docker-Rails-Generator
        ./bin/build-environment-for-building-app
    - uses: actions/cache@v3
      with:
        path: ${{ github.workspace }}/vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/*/Gemfile.lock') }}
    - uses: actions/cache@v3
      with:
        path: ${{ github.workspace }}/App/node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('**/*/package.json') }}
    - name: Build latest version of app
      run: |
        cd $GITHUB_WORKSPACE/Docker-Rails-Generator
        ./bin/build-latest-version
    - name: Pull docker image
      run: |
        cd $GITHUB_WORKSPACE/App
        docker pull ruby:3.0.1-alpine --quiet
        docker-compose pull --quiet
    - uses: satackey/action-docker-layer-caching@v0
      with:
        key: ${{ runner.os }}-docker-${{ hashFiles('**/*/Dockerfile') }}
        restore-keys: |
          ${{ runner.os }}-docker-
    - name: Cache Assets
      uses: actions/cache@v3
      with:
        path: |
          ${{ github.workspace }}/App/public/assets
          ${{ github.workspace }}/App/public/packs-test
        key: ${{ runner.os }}-assets-${{ hashFiles('**/*/yarn.lock') }}
    - name: Cache gems
      uses: actions/cache@v3
      with:
        path: |
          ${{ github.workspace }}/App/vendor/bundle
        key: ${{ runner.os }}-bundle-${{ hashFiles('**/*/Gemfile.lock') }}
    - name: Do the test still pass in our new template?
      run: |
        cd $GITHUB_WORKSPACE/Docker-Rails-Generator
        ./bin/test-latest-version
    - name: What would we be committing?
      run: |
        cd $GITHUB_WORKSPACE/App
        git status
